version: '1'

services:
  mongo_primary:
    image: mongo:${MONGO_DB_VER}
    container_name: mongo_primary
    ports:
      - "27017:27017"
    networks:
      - mongoCluster
      - yolo_to_mongo_primary
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo_primary

  mongo_1:
    image: mongo:${MONGO_DB_VER}
    container_name: mongo_1
    ports:
      - "27018:27017"
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo_1

  mongo_2:
    image: mongo:${MONGO_DB_VER}
    container_name: mongo_2
    ports:
      - "27019:27017"
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo_2

  polybot:
    image: polybot:${POLYBOT_VER}
    container_name: polybot
    ports:
      - "8443:8443"
    env_file:
      - .env

  yolo5_app:
    image: yolo5:0.0.1
    container_name: yolo5_app
    ports:
      - "8081:8081"
    volumes:
      - $HOME/aws/credentials:$HOME/aws/credentials
    env_file:
      - .env
    networks:
      - mongoCluster
      - yolo_to_mongo_primary
      - polybot_to_yolo

networks:
  mongoCluster:
    name: mongoCluster
    driver: bridge
  yolo_to_mongo_primary:
    name: yolo_to_mongo_primary
    driver: bridge
  polybot_to_yolo:
    name: polybot_to_yolo
    driver: bridge