name: Polybot Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP:  51.20.187.11 # replace to your EC2 instance public IP

jobs:
  PolybotBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd polybot
          
          # Login to DockerHub (comment out if you don't use DockerHub):         
          docker login -u ${{ secrets.DOCKER_REPO_USERNAME }} -p ${{ secrets.DOCKER_REPO_PASSWORD }}

          IMAGE_NAME=polybot:${{ github.run_number }}
          docker build -t polybot:$POLYBOT_VER .
          docker push galgu/polybot:$POLYBOT_VER

  Yolo5Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd yolo5
          
          docker login -u ${{ secrets.DOCKER_REPO_USERNAME }} -p ${{ secrets.DOCKER_REPO_PASSWORD }}

          IMAGE_NAME=yolo5:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  Deploy:
    name: Deploy Docker compose project
    runs-on: ubuntu-latest
    needs:
      - PolybotBuild
      - Yolo5Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Copy Compose files to the EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: docker-compose.yaml
          target: PolybotService/

      - name: Update the Docker Compose project in the EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # You deployment script here...
            
            sudo apt update && sudo apt install jq -y
            
            cd PolybotService/
            
            # Save telegram bot token in a secret file, to be used in docker-compose.yaml
            echo "${{ secrets.TELEGRAM_TOKEN }}" > telegram_bot_token.secret
            
            # Get the ngrok current domain (you should assume ngrok is already running in the EC2)
            NGROK_DOMAIN=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
            
            # Generate .env file
            echo """
            POLYBOT_IMG_NAME=polybot:${{ github.run_number }}
            YOLO5_IMG_NAME=yolo5:${{ github.run_number }}
            TELEGRAM_APP_URL=$NGROK_DOMAIN
            """ > .env
            
            # Take the service down
            docker compose down
            
            # Take it up with the current updated values
            docker compose up -d
